name: flutter_fetcher_state
description: A new Flutter package project.
version: 1.1.0
repository: https://github.com/andreaswierm/flutter_fetcher_state.git

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  provider: ">=6.0.0 <7.0.0"

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter
